name: Integration Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        integration:
          - content-resolution
          - parcel
          - postcss-cli
          - rollup
          - rollup-sass
          - tailwindcss-cli
          - vite
          - webpack-4
          - webpack-5
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Use cached node_modules (tailwindcss)
        id: cache-tailwindcss
        uses: actions/cache@v3
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('./package-lock.json') }}-${{ matrix.node-version }}-tailwindcss
          restore-keys: |
            nodeModules-

      - name: Install dependencies (main)
        if: steps.cache-tailwindcss.outputs.cache-hit != 'true'
        run: npm install

      - name: Use cached node_modules (tailwindcss)
        id: cache-tailwindcss-oxide
        uses: actions/cache@v3
        with:
          path: oxide/node_modules
          key: nodeModules-${{ hashFiles('./package-lock.json') }}-${{ matrix.node-version }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies (oxide)
        if: steps.cache-tailwindcss-oxide.outputs.cache-hit != 'true'
        run: npm run oxide:install

      - name: Build Tailwind CSS
        run: npx turbo run oxide:build

      - name: Use cached node_modules (integrations)
        id: cache-integrations
        uses: actions/cache@v3
        with:
          path: ./integrations/**/node_modules
          key: nodeModules-${{ hashFiles('./integrations/**/package-lock.json') }}-${{ matrix.node-version }}-${{ matrix.integration }}-integrations
          restore-keys: |
            nodeModules-

      - name: Install shared dependencies
        if: steps.cache-integrations.outputs.cache-hit != 'true'
        run: npm run install:integrations

      - name: Test ${{ matrix.integration }}
        run: npx turbo run test --filter=./integrations/${{ matrix.integration }}
